# Generated by Django 2.2 on 2020-02-13 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='request',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='helpdesc.Request'),
        ),
    ]
