# Generated by Django 2.2 on 2020-02-22 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesc', '0003_statushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'New'), ('2', 'In Progress'), ('3', 'Done'), ('4', 'Restored')], default='1', max_length=2)),
                ('status_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='resolution',
            field=models.CharField(blank=True, choices=[('1', 'Resolved'), ('2', 'Rejected')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'In Progress'), ('3', 'Done'), ('4', 'Restored')], default='1', max_length=2),
        ),
        migrations.DeleteModel(
            name='StatusHistory',
        ),
        migrations.AddField(
            model_name='status',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_name', to='helpdesc.Request'),
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
