# Generated by Django 2.1.2 on 2020-02-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesc', '0006_auto_20200223_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='flag_reopen',
            field=models.BooleanField(default=False),
        ),
    ]
